
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nakul
 */
public class Walk_in_costumer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Walk_in_costumer
     */
    public Walk_in_costumer() {
        initComponents();
        j1.setVisible(true);
        jButton7.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        Login = new javax.swing.JTextField();
        Logout = new javax.swing.JTextField();
        Comp_no = new javax.swing.JTextField();
        total_bill = new javax.swing.JTextField();
        paid = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ch_per_hr = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        total_time = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        j1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1232, 634));

        jLabel1.setText("Walk In Costumer");

        jLabel2.setText("ID :");

        jLabel3.setText("NAME:");

        jLabel4.setText("Login Time:");

        jLabel5.setText("Logut Time:");

        jLabel6.setText("Computer NO:");

        jLabel7.setText("Total Bill:");

        jLabel8.setText("Paid:");

        jLabel9.setText("Balance:");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Charge per Hour:");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Login", "Logut", "Computer No", "Bill", "Paid"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setText("Total Time Spend:");

        j1.setColumns(20);
        j1.setRows(5);
        jScrollPane2.setViewportView(j1);

        jButton6.setText("Show Bill");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Print Bill");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ID)
                            .addComponent(NAME)
                            .addComponent(Login)
                            .addComponent(Logout)
                            .addComponent(Comp_no)
                            .addComponent(total_bill)
                            .addComponent(paid)
                            .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(ch_per_hr)
                            .addComponent(total_time))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Comp_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ch_per_hr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(total_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(total_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ID.setText("");NAME.setText("");Login.setText("");Logout.setText("");balance.setText("");paid.setText("");total_bill.setText("");Comp_no.setText("");ch_per_hr.setText("");total_time.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cyber_cafe","root","");
            Statement st = con.createStatement();
            int id1 = Integer.parseInt(ID.getText());
            ResultSet rs = st.executeQuery("SELECT * FROM walk_in_costumer WHERE ID="+id1+" ");
            rs.next();
            NAME.setText(rs.getString("Name"));
            Login.setText(rs.getString("Arrival_time"));
            con.close();
        }
        catch(SQLException we){
            System.out.print(we);
            JOptionPane.showMessageDialog(this,"no RECORD Found ");
        }
        catch(NumberFormatException we){
           JOptionPane.showMessageDialog(this,"Please Fill All the Fields !");
        }
        
        LocalDateTime myDateObj = LocalDateTime.now();
    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("HH:mm:ss");

    String formattedDate = myDateObj.format(myFormatObj);
    System.out.println("After formatting: " + formattedDate);
    Logout.setText(formattedDate);
    paid.setText("0");
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        double total_hrs= 0;
        String login_time = Login.getText();
        String logout_time = Logout.getText();
        
        SimpleDateFormat sdf 
            = new SimpleDateFormat( 
                "HH:mm:ss");
        try {
            Date d1 = sdf.parse(login_time); 
            Date d2 = sdf.parse(logout_time); 
  
          
            long difference_In_Time = d2.getTime() - d1.getTime();
            long difference_In_Seconds = (difference_In_Time/ 1000) % 60; 
  
            long difference_In_Minutes = (difference_In_Time/ (1000 * 60))  % 60; 
  
            long difference_In_Hours = (difference_In_Time / (1000 * 60 * 60))% 24;
            
            if(0 ==difference_In_Hours   && difference_In_Minutes <=30 ){
                total_hrs = 0.5 ;
            }
            else{
                total_hrs = difference_In_Hours;
                if(difference_In_Minutes >30)total_hrs++;
            }
            total_time.setText(difference_In_Hours+":"+difference_In_Minutes+":"+difference_In_Seconds);
            int per_hrs  = Integer.parseInt(ch_per_hr.getText());
        int paid1  = Integer.parseInt(paid.getText());
        double total_bill1 = total_hrs *per_hrs;
        double balance1 = total_bill1-paid1;
        balance.setText(String.valueOf(balance1));
        total_bill.setText(String.valueOf(total_bill1));
        }
        catch (ParseException e) { 
            e.printStackTrace(); 
        }
        catch(NumberFormatException we){
           JOptionPane.showMessageDialog(this,"Please Fill All the Fields !");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cyber_cafe","root","");
            Statement st = con.createStatement();
            int id1 = Integer.parseInt(ID.getText());
            String name1 = NAME.getText();
            String arr_time = Login.getText();
            String uk = Logout.getText();
            int comp_no1 = Integer.parseInt(Comp_no.getText());
            int bill0 = Integer.parseInt(total_bill.getText());
            int paid0 = Integer.parseInt(paid.getText());
            int blalnce0 = Integer.parseInt(balance.getText());
            st.executeUpdate("UPDATE  walk_in_costumer set Exit_time='"+uk+"' ,Computer_no="+comp_no1+", Amount_paid="+paid0+",Amount_balance="+blalnce0+" ,Bill="+bill0+"  WHERE ID="+id1+" ");
            con.close();
            JOptionPane.showMessageDialog(this,"Record Submitted");
        }
        catch(SQLException we){
           System.out.print(we);
        }
        catch(NumberFormatException we){
           JOptionPane.showMessageDialog(this,"Please Fill All the Fields !");
        }
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cyber_cafe","root","");
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM `walk_in_costumer`");
            while(rs.next())
            {
                String id =  String.valueOf(rs.getInt("ID"));
                String name = rs.getString("Name");
                String arrived = rs.getString("Arrival_time");
                String exit = rs.getString("Exit_time");
                String comp_no1 = String.valueOf(rs.getInt("Computer_no"));
                String bill = String.valueOf(rs.getInt("Amount_balance"));
                String bal = String.valueOf(rs.getInt("Amount_paid"));
                
                String tbData []= {id,name,arrived,exit,comp_no1,bill,bal};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
            }
        catch(SQLException we){
           System.out.print(we);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Delete 
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cyber_cafe","root","");
            Statement st = con.createStatement();
            int id = Integer.parseInt(ID.getText());
            st.executeUpdate("DELETE FROM walk_in_costumer WHERE ID="+id+" ");
            con.close();
            JOptionPane.showMessageDialog(this,"RECORD DLETED SucessFully");
            ID.setText("");
            NAME.setText("");
            Login.setText("");
            Logout.setText("");
        balance.setText("");
        paid.setText("");
        total_bill.setText("");
        Comp_no.setText("");
        ch_per_hr.setText("");
        total_time.setText("");

        }
        catch(SQLException we){
            System.out.print(we);
        }
        catch(NumberFormatException we){
           JOptionPane.showMessageDialog(this,"Please Fill All the Fields !");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        j1.setVisible(true);
        jButton7.setVisible(true);
        j1.setText("\t\t\t Cyber Cafe Bill\n\n"
                +  "\t\t ID"+ID.getText() 
                    +"\n\n\t\tName :"+NAME.getText()
                +"\n\n\t\tLogin Time :"+Login.getText()
                +"\n\n\t\tLogout Time :"+Logout.getText()
                +"\n\n\t\tTotal Bill:"+total_bill.getText()
                +"\n\n\t\tAmount Paid:"+paid.getText()
                +"\n\n\t\tBalnce Amount:"+balance.getText()
                +"\n\n\t\tComputer No:"+Comp_no.getText()
                +"\n\n\\n\n\tThank You........:"
        );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        j1.setForeground(Color.BLACK);
        try {
            // TODO add your handling code here:
            j1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(member_charges.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Comp_no;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField Logout;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField ch_per_hr;
    private javax.swing.JTextArea j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField total_bill;
    private javax.swing.JTextField total_time;
    // End of variables declaration//GEN-END:variables
}
